package growthcraft.bees.shared.init;

import growthcraft.cellar.shared.definition.BlockBoozeDefinition;
import growthcraft.core.shared.definition.BlockDefinition;

public class GrowthcraftBeesBlocks {
    private GrowthcraftBeesBlocks() {
    }

    public static BlockDefinition beeBox;
    public static BlockDefinition beeHive;

    public static BlockBoozeDefinition[] meadBoozeFluidBlocks;    // NOTE: Not including honey itself, which is a part generated by FluidFactory
}
