name: Growthcraft Tagged Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*'

jobs:
  build:

    name: Build and Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: 8
        distribution: adopt
    - name: Setup Gradle
      run: chmod +x gradlew
    - name: Setup CI Workspace
      run:  ./gradlew setupCIWorkspace
    - name: Build with Gradle
      run: ./gradlew build
    - name: Create GitHub Release
      uses: Roang-zero1/github-create-release-action@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload to GitHub
      uses: Alatyami/github-upload-release-artifacts-action@master
      with:
        args: build/libs/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
